# Generated by Django 5.2.11 on 2026-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_and_Todo_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
