# Generated by Django 5.2.11 on 2026-02-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_and_Todo_Manager', '0002_alter_subtask_title_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
