# Generated by Django 5.2.11 on 2026-02-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_and_Todo_Manager', '0003_alter_subtask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
