# Generated by Django 5.2.11 on 2026-02-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_and_Todo_Manager', '0004_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
