# Generated by Django 5.2.11 on 2026-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_and_Todo_Manager', '0005_alter_category_options_alter_priority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
